apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.synapsekitMetrics.service.name }}
  labels:
    app.kubernetes.io/name: {{ include "synapsekit-observability.name" . }}
spec:
  type: {{ .Values.synapsekitMetrics.service.type }}
  ports:
    - port: {{ .Values.synapsekitMetrics.service.port }}
      targetPort: {{ .Values.synapsekitMetrics.service.port }}
      name: http
  selector:
    app: synapsekit
